version: "3"

services:
  mongo:
    image: mongo:4.2
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_DATABASE=api
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - mongo
    volumes:
      - ./api:/code
    command: sh -c './wait-for-it.sh mongo:27019 -t 30 -- uvicorn main:app --host 0.0.0.0 --port 80 --reload'

  dashboard:
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - api
    volumes:
      - ./dashboard:/code:cached
    command:
      sh -c 'npm run dev'
